#!/usr/bin/perl
use strict;
use warnings;
use Filesys::DfPortable;
use Time::Piece;

my $PORT = 2346;
my $ServerName ="";
my $NumUsers = 0;
my $RefreshRate = 65;
my $ProcessName = "java";
my $Version = "1.0.0";
my $PrefsFilename = "$ENV{HOME}/.listusersrc";
my $DEBUGMODE = "";
my $EDITOR = "/usr/bin/nano";
my $OutputFile = "";
my $ref = dfportable("/", 1024);
my $SpaceStatus = "green";
my $SupportLink = "";

print "listusers - Lists Users Logged Into MegaMek v$Version\n";
print "======================================================\n";
# Ensure the script is run with root privileges to read /proc/PID/fd/
if ($> != 0) {
	die "Error: This script must be run as root (sudo) to inspect process file descriptors.\n";
}

sub DebugPrint
{
	my $argument = shift;
	if ($DEBUGMODE ne "")
	{
		print $argument;
	}
}

sub pretty_print_kb
{
	my $kb = shift;
	my @units = ('KB', 'MB', 'GB', 'TB', 'PB');
	my $unit_idx = 0;

	# Since input is in KB, scale up if >= 1024 KB
	#while ($kb >= 1024 && $unit_idx < $@units - 1)
	while ($kb >= 1024 && $unit_idx < @units - 1)
	{
		$kb /= 1024;
		$unit_idx++;
	}

	return sprintf("%.2f %s", $kb, $units[$unit_idx]);
}

my $defaultfile = <<'END_TEMPLATE';
# Put Server name here:
Test MegaMek
# Put port here
2346
# Refresh rate - How often the webpage will get reloaded.
65
# Process to check
java
# Editor to use
/usr/bin/nano
# Output file
/var/www/html/MM_Stats.html
# Support Link
https://megamekfans.gameplayer.club
# Get more apps like this at https://marisa-apps.retro-os.live
END_TEMPLATE

my $num_args = $#ARGV + 1;
if ($num_args != 0)
{
	if ($ARGV[0] eq "prefs")
	{
		system("$EDITOR $PrefsFilename");
		exit 0;
	}
	elsif ($ARGV[0] eq "debug")
	{
		$DEBUGMODE = "debug";
	}
	else
	{
		print "Invalid option - only options are \"prefs\" and \"debug\".\n";
	}
}
if (! -f $PrefsFilename)
{
	print "Settings file $PrefsFilename not found, creating it...\n";
	open(FILEOUT, '>', $PrefsFilename) or die $!;
	# print FILEOUT "$defaultfile\n";
	print FILEOUT "$defaultfile";
	close(FILEOUT);
	system("$EDITOR $PrefsFilename");
	print "Prefs modified - rerun this script\n";
	exit 0;
}

open(FILEIN, '<', $PrefsFilename) or die $!;
my $LastLine = 0;
while(<FILEIN>)
{
	# print $_;
	if ((substr($_, 0, 1) eq "#") || ($_ eq ""))
	{
		# skip over comments and blank lines
		next;
	}
	chop();
	if ($LastLine == 0)
	{
		$ServerName = $_;
		$LastLine++;
		DebugPrint("saw server name '$ServerName'\n");
	}
	elsif ($LastLine == 1)
	{
		$PORT = $_;
		DebugPrint("saw port '$PORT'\n");
		$LastLine++;
	}
	elsif ($LastLine == 2)
	{
		$RefreshRate = $_;
		$LastLine++;
		DebugPrint("saw refreshrate '$RefreshRate'\n");
	}
	elsif ($LastLine == 3)
	{
		$ProcessName = $_;
		$LastLine++;
		DebugPrint("saw processname '$ProcessName'\n");
	}
	elsif ($LastLine == 4)
	{
		$EDITOR = $_;
		$LastLine++;
		DebugPrint("saw editor '$EDITOR'\n");
	}
	elsif ($LastLine == 5)
	{
		$OutputFile = $_;
		$LastLine++;
		DebugPrint("saw outputfile '$OutputFile'\n");
	}
	elsif ($LastLine == 6)
	{
		$SupportLink = $_;
		$LastLine++;
		DebugPrint("saw supportlink '$SupportLink'\n");
	}
}
close(FILEIN);

open(FILEOUT, '>', $OutputFile) or die $!;

my $IsRunning = `pgrep $ProcessName`;
if ($IsRunning eq "")
{
	print "Process $ProcessName is not running\n";
	exit 0;
}

my $PSCommand = "ps -p \$(pidof $ProcessName) -o etime=";
my $ProcTime = `$PSCommand`;
$ProcTime =~ s/^\s+//; # Removes leading whitespace
$ProcTime =~ s/\s+$//; # Removes trailing whitespace

my $Uptime = `uptime -p`;
my $FreeSpace = pretty_print_kb($ref->{bavail});
my $RawFreeSpace = $ref->{bavail};
if ($RawFreeSpace < 300000)
{
	$SpaceStatus = "red";
}

my $free_ram = `free -m | awk '/^Mem:/{print \$4}'`;
chop($free_ram);
my $RamStatus = "green";
#print "Free Memory: $free_ram MB\n";
if ($free_ram < 24)
{
	$RamStatus = "red";
}

my $OutputTop = <<"END_MESSAGE";
<html>
<head>
	<title>The $ServerName MegaMek server</title>
	<meta http-equiv="refresh" content="$RefreshRate">
</head>
<body>
	<h2 align=center>The $ServerName MegaMek server</h2>
	<p align=center>MegaMek has been up for <span style="color: green;">$ProcTime</span>, System has been <span style="color: green;">$Uptime</span>, Free Space: <span style="color: $SpaceStatus;">$FreeSpace</span>, Free Memory: <span style="color: $RamStatus;">$free_ram MB</span></p>
	<p>User Sessions:</p>
	<table border=2>
	<tr><th width=250>User IP</th><th width=250>Time Online</th></tr>
END_MESSAGE

print FILEOUT "$OutputTop\n";

# Subroutine to calculate human-readable duration strings
sub calculate_duration
{
	my ($start_time) = @_;
	my $now = time();
	my $diff = $now - $start_time;

	if ($diff < 0) { $diff = 0; }

	my $days	= int($diff / 86400);
	my $hours	= int(($diff % 86400) / 3600);
	my $minutes	= int(($diff % 3600) / 60);
	my $seconds	= $diff % 60;

	my $duration_str = "";
	if ($days > 0)		{ $duration_str .= "${days}d "; }
	if ($hours > 0)		{ $duration_str .= "${hours}h "; }
	if ($minutes > 0)	{ $duration_str .= "${minutes}m "; }
	$duration_str .= "${seconds}s";

	return $duration_str;
}

# Run 'ss' to get established TCP connections along with process details (-p)
open(my $fh, "-|", "ss -tneump 2>/dev/null") or die "Failed to execute ss: $!";

while (my $line = <$fh>)
{
	chomp($line);
	next if $. == 1; # Skip headers

	# Split columns based on whitespace
	my @cols = split(/\s+/, $line);
	next if @cols < 6;
	my $IsDesired = index($cols[6], "java");
	if ($IsDesired < 1)
	{
		next;
	}
	DebugPrint "cols = @cols\n";
	my $state = $cols[0];
	my $local = $cols[4];
	my $peer = $cols[5];
	DebugPrint "peer = $peer\n";
	$IsDesired = index($local, "$PORT");	# ZZZ
	if ($IsDesired < 1)
	{
		next;
	}

	# Extract PID and FD from the users field, e.g., users:(("nginx",pid=1234,fd=5))
	if ($line =~ /pid=(\d+),fd=(\d+)/)
	{
		my $pid = $1;
		my $fd = $2;
		DebugPrint "pid = $pid\n";

		my $fd_path = "/proc/$pid/stat";
		if (-e $fd_path)
		{
			# Get the modification time (creation time of the socket FD link)
			my $mtime = (stat($fd_path))[9];
			DebugPrint "mtime = $mtime\n";

			if ($mtime)
			{
				my $duration = calculate_duration($mtime);
				#printf("%-21s %-21s %-8s %-15s %s\n", $local, $peer, $pid, $state, $duration);
				$NumUsers++;
				#print $line;
				(my $foo1,my $foo2,my $foo3,my $foo4,my $UserIP,my $foo5) = split(' ',$line);
				my $DotPos = rindex($peer, ":");
				my $PlainIP = substr($peer, 0, $DotPos);
				$PlainIP = substr($PlainIP, 1);
				chop ($PlainIP);
				my $RemotePort = substr($peer, $DotPos + 1);
				print FILEOUT "<tr><td align = center><span style=\"color: green;\">$PlainIP</span></td><td align = center>$duration</td></tr>\n";
			}
		}
	}
}
close($fh);

my $current_time = localtime();
my $OutputBottom = <<"END_MESSAGE";
	</table>
	<p>Saw <span style="color: red;">$NumUsers</span> online player(s)</p>
	<p>Get support <a href=\"$SupportLink\">here</a></p>
	<hr>
	<b>Last Updated at: $current_time</b>
</body>
</html>
END_MESSAGE

print FILEOUT "$OutputBottom\n";
close(FILEOUT);
exit 0;

