#!/usr/bin/perl
use strict;
use warnings;

my $PORT = 2346;
my $ServerName ="";
my $NumUsers = 0;
my $RefreshRate = 65;
my $ProcessName = "java";
my $PSCommand = "ps -p \$(pidof $ProcessName) -o etime=";
my $ProcTime = `$PSCommand`;
$ProcTime =~ s/^\s+//; # Removes leading whitespace
$ProcTime =~ s/\s+$//; # Removes trailing whitespace
my $Version = "1.0.0";

my $OutputTop = <<"END_MESSAGE";
<html>
<head>
	<title>The $ServerName MegaMek server</title>
	<meta http-equiv="refresh" content="$RefreshRate">
</head>
<body>
	<h2 align=center>The $ServerName MegaMek server</h2>
	<p>MegaMek has been up for $ProcTime</p>
	<p>User Sessions:</p>
	<table border=2>
	<tr><th width=50%>User IP</th><th width=50%>Some Data</th></tr>
END_MESSAGE

print "$OutputTop\n";

my $cmd = "netstat -an | grep ESTABLISHED";
open(my $fh, "-|", $cmd) or die "Failed to run '$cmd': $!";

while (my $line = <$fh>)
{
	next if $line =~ /^\s*$/;

	# Match :2346 (IPv4/IPv6 variants) anywhere in the line,
	# including cases like ":::2346" or "[::]:2346"
	if ($line =~ /:\Q$PORT\E\b/)
	{
		$NumUsers++;
		#print $line;
		(my $foo1,my $foo2,my $foo3,my $foo4,my $UserIP,my $foo4) = split(' ',$line);
		print "<tr><td>>$UserIP</td><td>Some Data</td></tr>\n";
	}
}

close($fh);

my $OutputBottom = <<"END_MESSAGE";
	</table>
	<p>Saw $NumUsers online player(s)</p>
</body>
</html>
END_MESSAGE

print "$OutputBottom\n";
exit 0;

